spring.application.name=web-crawler

# Database URL, Username, and Password
# spring.datasource.url=jdbc:mysql://localhost:3306/your_database_name?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=root
spring.datasource.password=your_password

# ==========================================
# JPA / Hibernate Configuration
# ==========================================
# Options: create, create-drop, update, validate, none
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries and format them in console logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate Dialect (Recommended for MySQL 8+)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
